name: allChannels Updater
on:
 schedule:
   - cron: "0 0 */5 * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tata Sky IPTV allChannels.json Updater
      run: |
            git config --global user.name "Shra1V32"
            git config --global user.email "namanageshwar@outlook.com"
            git clone "https://${{ secrets.my_token }}@github.com/Shra1V32/Tata-Sky-IPTV.git"
            cd Tata-Sky-IPTV/code_samples
            channels=$(python3 allChannels.py | tail -n1)
            cd ..
            git add .
            git commit -m "Updated allChannels.json of $channels channels at "$(date -u +%D-%T%P)""
            git push
            exit